// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: Translator.proto

package translator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslatingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UzWord string `protobuf:"bytes,1,opt,name=UzWord,proto3" json:"UzWord,omitempty"`
}

func (x *TranslatingRequest) Reset() {
	*x = TranslatingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Translator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatingRequest) ProtoMessage() {}

func (x *TranslatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Translator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatingRequest.ProtoReflect.Descriptor instead.
func (*TranslatingRequest) Descriptor() ([]byte, []int) {
	return file_Translator_proto_rawDescGZIP(), []int{0}
}

func (x *TranslatingRequest) GetUzWord() string {
	if x != nil {
		return x.UzWord
	}
	return ""
}

type TranslatingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnWord string `protobuf:"bytes,1,opt,name=EnWord,proto3" json:"EnWord,omitempty"`
}

func (x *TranslatingResponse) Reset() {
	*x = TranslatingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Translator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslatingResponse) ProtoMessage() {}

func (x *TranslatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Translator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslatingResponse.ProtoReflect.Descriptor instead.
func (*TranslatingResponse) Descriptor() ([]byte, []int) {
	return file_Translator_proto_rawDescGZIP(), []int{1}
}

func (x *TranslatingResponse) GetEnWord() string {
	if x != nil {
		return x.EnWord
	}
	return ""
}

var File_Translator_proto protoreflect.FileDescriptor

var file_Translator_proto_rawDesc = []byte{
	0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x2c,
	0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x7a, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x7a, 0x57, 0x6f, 0x72, 0x64, 0x22, 0x2d, 0x0a, 0x13,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x6e, 0x57, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x6e, 0x57, 0x6f, 0x72, 0x64, 0x32, 0x62, 0x0a, 0x11, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0d, 0x5a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Translator_proto_rawDescOnce sync.Once
	file_Translator_proto_rawDescData = file_Translator_proto_rawDesc
)

func file_Translator_proto_rawDescGZIP() []byte {
	file_Translator_proto_rawDescOnce.Do(func() {
		file_Translator_proto_rawDescData = protoimpl.X.CompressGZIP(file_Translator_proto_rawDescData)
	})
	return file_Translator_proto_rawDescData
}

var file_Translator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Translator_proto_goTypes = []any{
	(*TranslatingRequest)(nil),  // 0: translator.TranslatingRequest
	(*TranslatingResponse)(nil), // 1: translator.TranslatingResponse
}
var file_Translator_proto_depIdxs = []int32{
	0, // 0: translator.TranslatorService.Translator:input_type -> translator.TranslatingRequest
	1, // 1: translator.TranslatorService.Translator:output_type -> translator.TranslatingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Translator_proto_init() }
func file_Translator_proto_init() {
	if File_Translator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Translator_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TranslatingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Translator_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TranslatingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Translator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Translator_proto_goTypes,
		DependencyIndexes: file_Translator_proto_depIdxs,
		MessageInfos:      file_Translator_proto_msgTypes,
	}.Build()
	File_Translator_proto = out.File
	file_Translator_proto_rawDesc = nil
	file_Translator_proto_goTypes = nil
	file_Translator_proto_depIdxs = nil
}
